---
- name: Converge
  hosts: all
  become: true

  vars_files:
    - test-vars.yml

  vars:
    # Deploy from the Drupal for Kubernetes example project.
    drupal_deploy: true
    drupal_deploy_repo: "https://github.com/nholuong/drupal-for-kubernetes.git"
    drupal_deploy_dir: /var/www/drupal
    drupal_domain: "test.pidramble.com"

    # Disable Composer-based codebase setup.
    drupal_build_composer_project: false
    drupal_build_composer: false
    drupal_composer_dependencies: []

  pre_tasks:
    - import_tasks: test-setup.yml

  roles:
    - name: nholuong.repo-remi
      when: ansible_os_family == "RedHat"
    - role: nholuong.repo-dotdeb
      when: ansible_distribution == 'Debian'
    - role: nholuong.apache
    - role: nholuong.mysql
    - role: nholuong.php-versions
    - role: nholuong.php
    - role: nholuong.php-mysql
    - role: nholuong.git
    - role: nholuong.composer
    - role: nholuong.drush
    - role: nholuong.drupal
